{% set name = "tinysegmenter" %}
{% set version = "0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tinysegmenter-{{ version }}.tar.gz
  sha256: ed1f6d2e806a4758a73be589754384cbadadc7e1a414c81a166fc9adf2d40c6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.6
  run:
    - python >=2.6

test:
  imports:
    - tinysegmenter
  commands:
    - pip check
    - python tests/test.py
  requires:
    - pip
    - python >=2.6
  source_files:
    - tests

about:
  home: http://tinysegmenter.tuxfamily.org/
  summary: Very compact Japanese tokenizer
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - BastianZim
